version: "3"

services:
  mongo:
    image: mongo:5.0.1
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-alpha
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
    - 8081:8081
    depends_on:
      - mongo

  redis:
    image: redis:5.0
    ports:
    - 6379:6379
#
#  backend:
#    image: backend
#    build:
#      dockerfile: ./backend/Dockerfile
#      context: .
#    environment:
#      MONGO_HOST: mongo
#    ports:
#    - 8080:8080
